"""initial schema

Revision ID: 265e405ccf13
Revises: 
Create Date: 2026-02-17 12:33:07.770447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '265e405ccf13'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=True)
    op.create_table('ai_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('diet', 'exercise', 'coaching', name='recommendation_type_enum'), nullable=False),
    sa.Column('context_summary', sa.Text(), nullable=True),
    sa.Column('prompt_used', sa.Text(), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('rag_sources', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('model_used', sa.String(length=50), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ai_recommendations_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_recommendations'))
    )
    op.create_index('ix_ai_recommendations_user_type', 'ai_recommendations', ['user_id', 'type'], unique=False)
    op.create_table('diet_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('meal_type', sa.Enum('breakfast', 'lunch', 'dinner', 'snack', name='meal_type_enum'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('ai_analyzed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_diet_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diet_logs'))
    )
    op.create_index('ix_diet_logs_user_date', 'diet_logs', ['user_id', 'log_date'], unique=False)
    op.create_table('exercise_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exercise_date', sa.Date(), nullable=False),
    sa.Column('exercise_name', sa.String(length=100), nullable=False),
    sa.Column('muscle_group', sa.Enum('chest', 'back', 'shoulder', 'legs', 'arms', 'core', 'cardio', 'full_body', name='muscle_group_enum'), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_exercise_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_logs'))
    )
    op.create_index('ix_exercise_logs_user_date', 'exercise_logs', ['user_id', 'exercise_date'], unique=False)
    op.create_index('ix_exercise_logs_user_muscle', 'exercise_logs', ['user_id', 'muscle_group'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refresh_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refresh_tokens'))
    )
    op.create_index('ix_refresh_tokens_token', 'refresh_tokens', ['token'], unique=True)
    op.create_index('ix_refresh_tokens_user', 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('height_cm', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('gender', sa.Enum('male', 'female', 'other', name='gender_enum'), nullable=True),
    sa.Column('goal', sa.Enum('bulk', 'diet', 'maintain', name='goal_enum'), nullable=False),
    sa.Column('activity_level', sa.Enum('sedentary', 'light', 'moderate', 'active', 'very_active', name='activity_level_enum'), nullable=True),
    sa.Column('allergies', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('food_preferences', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), nullable=False),
    sa.Column('tdee_kcal', sa.Integer(), nullable=True),
    sa.Column('target_calories', sa.Integer(), nullable=True),
    sa.Column('target_protein_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('target_carbs_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('target_fat_g', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_profiles_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('user_id', name=op.f('uq_user_profiles_user_id'))
    )
    op.create_table('diet_log_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diet_log_id', sa.Integer(), nullable=False),
    sa.Column('food_name', sa.String(length=200), nullable=False),
    sa.Column('serving_size', sa.String(length=50), nullable=True),
    sa.Column('calories', sa.Numeric(precision=7, scale=1), nullable=False),
    sa.Column('protein_g', sa.Numeric(precision=6, scale=1), server_default=sa.text('0'), nullable=False),
    sa.Column('carbs_g', sa.Numeric(precision=6, scale=1), server_default=sa.text('0'), nullable=False),
    sa.Column('fat_g', sa.Numeric(precision=6, scale=1), server_default=sa.text('0'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['diet_log_id'], ['diet_logs.id'], name=op.f('fk_diet_log_items_diet_log_id_diet_logs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_diet_log_items'))
    )
    op.create_index('ix_diet_log_items_log_id', 'diet_log_items', ['diet_log_id'], unique=False)
    op.create_table('exercise_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_log_id', sa.Integer(), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=True),
    sa.Column('is_completed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_log_id'], ['exercise_logs.id'], name=op.f('fk_exercise_sets_exercise_log_id_exercise_logs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercise_sets'))
    )
    op.create_index('ix_exercise_sets_log_id', 'exercise_sets', ['exercise_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exercise_sets_log_id', table_name='exercise_sets')
    op.drop_table('exercise_sets')
    op.drop_index('ix_diet_log_items_log_id', table_name='diet_log_items')
    op.drop_table('diet_log_items')
    op.drop_table('user_profiles')
    op.drop_index('ix_refresh_tokens_user', table_name='refresh_tokens')
    op.drop_index('ix_refresh_tokens_token', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ix_exercise_logs_user_muscle', table_name='exercise_logs')
    op.drop_index('ix_exercise_logs_user_date', table_name='exercise_logs')
    op.drop_table('exercise_logs')
    op.drop_index('ix_diet_logs_user_date', table_name='diet_logs')
    op.drop_table('diet_logs')
    op.drop_index('ix_ai_recommendations_user_type', table_name='ai_recommendations')
    op.drop_table('ai_recommendations')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
