"""add_weight_logs_table

Revision ID: a3811b7dab02
Revises: 0e0918445906
Create Date: 2026-03-21 21:43:30.933416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3811b7dab02'
down_revision: Union[str, Sequence[str], None] = '0e0918445906'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weight_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=1), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_weight_logs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_weight_logs'))
    )
    op.create_index('ix_weight_logs_user_date', 'weight_logs', ['user_id', 'log_date'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weight_logs_user_date', table_name='weight_logs')
    op.drop_table('weight_logs')
    # ### end Alembic commands ###
