"""Claude Code·Codex 역할 파일 생성기.

harness/agents.toml(역할·모델·effort·허용 경로) + harness/roles/<role>.md(역할 본문)
→ .claude/agents/<role>.md, .codex/agents/<role>.toml
harness/agents.toml [lead] (+ .mcp.json이 있으면 그 MCP 서버) → .codex/config.toml
.claude/skills/** → .agents/skills/** (Codex용 사본. Windows core.symlinks=false 체크아웃에서는
심볼릭 링크가 링크 텍스트 파일로 풀리므로 링크 대신 사본을 생성하고 drift로 관리한다)

공통 규칙 AGENTS.md는 Claude Code(CLAUDE.md의 @AGENTS.md)와 Codex(루트 AGENTS.md 자동 적재)가
각자 불러오므로 역할 파일에 복사하지 않고 먼저 읽으라는 안내만 넣는다.
그래서 AGENTS.md만 고쳐서는 역할 파일이 바뀌지 않는다.

    python scripts/harness.py render          # 생성·갱신
    python scripts/harness.py render --check  # 원본과 일치하는지만 검사 (drift면 exit 1)

생성물은 직접 편집하지 않는다. 원본을 고치고 render를 다시 돌린다.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CONFIG = ROOT / "harness" / "agents.toml"
COMMON = ROOT / "AGENTS.md"
_POINTER = (
    "# AI Health Trainer 개발 규칙\n\n"
    "공통 규칙 원본은 AGENTS.md다. {loader} "
    "적재되지 않았으면 작업을 시작하기 전에 AGENTS.md를 읽는다. "
    ".env 읽기 금지와 테스트·검증에서 실제 Gemini 호출 금지는 이 역할에도 그대로 적용된다.\n"
)
COMMON_POINTER = _POINTER.format(loader="CLAUDE.md를 통해 프로젝트 메모리로 적재되며,")
CODEX_POINTER = _POINTER.format(loader="Codex가 저장소 루트의 지시 파일로 적재하며,")
ROLES_DIR = ROOT / "harness" / "roles"
SKILLS_DIR = ROOT / ".claude" / "skills"
OUTPUT_DIR = ROOT / ".claude" / "agents"
CODEX_DIR = ROOT / ".codex"
CODEX_SKILLS_DIR = ROOT / ".agents" / "skills"
MCP_CONFIG = ROOT / ".mcp.json"
MARKER = "Generated by scripts/harness.py"
READ_TOOLS = ("Read", "Glob", "Grep")
# 역할 파일에 tools를 적으면 그 밖의 도구는 주어지지 않는다(2026-09-25 실측: Skill·MCP 도구 없음).
# 역할 본문이 지시하는 스킬을 부를 수 있도록 Skill을, GitNexus 스킬이 쓰는 그래프 조회를 위해
# 읽기 전용 GitNexus MCP 도구를 모든 역할에 준다. 목록은 .claude/settings.json allow와 같아야 한다.
GITNEXUS_READ_TOOLS = tuple(
    f"mcp__gitnexus__{name}"
    for name in ("list_repos", "query", "context", "impact", "detect_changes", "trace", "explain")
)
READ_ONLY_TOOLS = READ_TOOLS + ("Skill",) + GITNEXUS_READ_TOOLS
WRITE_TOOLS = READ_ONLY_TOOLS + ("Edit", "Write", "Bash")
REQUIRED_FIELDS = {
    "description", "claude_model", "codex_model", "effort", "read_only", "allowed_paths",
}
LEAD_FIELDS = {"claude_model", "codex_model", "effort"}
# Codex 한 세션에서 동시에 돌릴 하위 에이전트 수. backend·frontend 병렬 위임까지만 둔다.
CODEX_MAX_THREADS = 2


class HarnessError(RuntimeError):
    """원본 설정이 잘못됐거나 생성 대상이 아닌 파일이 자리에 있을 때."""


def _read(path: Path) -> str:
    if not path.is_file():
        raise HarnessError(f"원본 파일이 없습니다: {path.relative_to(ROOT).as_posix()}")
    return path.read_text(encoding="utf-8").rstrip() + "\n"


def _check_fields(table: str, values: dict, required: set[str], display: dict) -> None:
    missing = required - set(values)
    if missing:
        raise HarnessError(f"{table}에 필드가 없습니다: {', '.join(sorted(missing))}")
    for key in ("claude_model", "codex_model"):
        if values[key] not in display:
            raise HarnessError(f"[display.models]에 {values[key]} 표기명이 없습니다.")


def _toml_lines(fields: dict) -> str:
    # 문자열·불리언·정수·문자열 목록만 쓰므로 JSON 표기가 그대로 TOML 값이 된다.
    return "".join(f"{key} = {json.dumps(value, ensure_ascii=False)}\n" for key, value in fields.items())


def _codex_config(lead: dict) -> str:
    """lead 모델과 (있으면) .mcp.json의 MCP 서버로 Codex 프로젝트 설정을 만든다."""
    servers: dict = {}
    if MCP_CONFIG.is_file():
        servers = json.loads(_read(MCP_CONFIG)).get("mcpServers") or {}
    parts = [
        f"# {MARKER}\n",
        _toml_lines({
            "model": lead["codex_model"],
            "model_reasoning_effort": lead["effort"],
            "approval_policy": "on-request",
            "sandbox_mode": "workspace-write",
        }),
        "\n[sandbox_workspace_write]\nnetwork_access = false\n",
        f"\n[agents]\nmax_concurrent_threads_per_session = {CODEX_MAX_THREADS}\n",
    ]
    for name, server in servers.items():
        if "command" not in server:
            raise HarnessError(f".mcp.json의 {name}: command가 없는 MCP 서버는 옮기지 않습니다.")
        key = json.dumps(name)
        parts.append(f"\n[mcp_servers.{key}]\n")
        parts.append(_toml_lines({"command": server["command"], "args": server.get("args", [])}))
        if server.get("env"):
            parts.append(f"\n[mcp_servers.{key}.env]\n{_toml_lines(server['env'])}")
    return "".join(parts)


def _skill_mirror() -> dict[str, str]:
    """.claude/skills/** 를 .agents/skills/** 로 복사할 {저장소 상대 경로: 내용}."""
    if not SKILLS_DIR.is_dir():
        return {}
    outputs: dict[str, str] = {}
    for path in sorted(SKILLS_DIR.rglob("*")):
        if path.is_file():
            rel = path.relative_to(SKILLS_DIR).as_posix()
            outputs[f".agents/skills/{rel}"] = path.read_text(encoding="utf-8")
    return outputs


def _is_marked(rel: str) -> bool:
    """마커 주석을 넣는 생성물인지. 스킬 사본은 원본을 그대로 복사하므로 마커가 없다."""
    return rel.startswith((".claude/agents/", ".codex/"))


def generated() -> dict[str, str]:
    """생성물 전체를 {저장소 상대 경로: 내용}으로 반환한다."""
    config = tomllib.loads(_read(CONFIG))
    roles = config.get("roles") or {}
    if not roles:
        raise HarnessError("agents.toml에 [roles.*]가 없습니다.")
    display = (config.get("display") or {}).get("models") or {}
    lead = config.get("lead") or {}
    _check_fields("[lead]", lead, LEAD_FIELDS, display)
    _read(COMMON)  # 안내가 가리키는 원본이 있어야 한다
    outputs: dict[str, str] = {}
    for name, role in roles.items():
        _check_fields(f"roles.{name}", role, REQUIRED_FIELDS, display)
        body = _read(ROLES_DIR / f"{name}.md")
        allowed = ", ".join(role["allowed_paths"]) or "없음 (읽기 전용)"
        role_text = f"{body}\n허용 경로 후보: {allowed}\n"
        prompt = f"{COMMON_POINTER}\n{role_text}"
        tools = READ_ONLY_TOOLS if role["read_only"] else WRITE_TOOLS
        source = json.dumps(role, sort_keys=True, ensure_ascii=False) + role_text
        digest = hashlib.sha256(source.encode("utf-8")).hexdigest()
        frontmatter = "\n".join(
            [
                "---",
                f"name: {name}",
                f"description: {json.dumps(role['description'], ensure_ascii=False)}",
                f"model: {role['claude_model']}",
                f"effort: {role['effort']}",
                f"tools: {', '.join(tools)}",
                "---",
            ]
        )
        outputs[f".claude/agents/{name}.md"] = (
            f"{frontmatter}\n<!-- {MARKER}; source_sha256={digest} -->\n\n{prompt}"
        )
        outputs[f".codex/agents/{name}.toml"] = f"# {MARKER}; source_sha256={digest}\n" + _toml_lines({
            "name": name,
            "description": role["description"],
            "model": role["codex_model"],
            "model_reasoning_effort": role["effort"],
            # 선언은 두지만 Codex 0.156 실측에서 하위 에이전트는 lead 샌드박스를 물려받았다.
            "sandbox_mode": "read-only" if role["read_only"] else "workspace-write",
            "developer_instructions": f"{CODEX_POINTER}\n{role_text}",
        })
    outputs[".codex/config.toml"] = _codex_config(lead)
    outputs.update(_skill_mirror())
    return outputs


def _stale_files(outputs: dict[str, str]) -> list[Path]:
    """원본이 사라진 생성물. 마커가 있는 역할 파일과 스킬 사본 디렉터리의 남은 파일."""
    candidates = [*OUTPUT_DIR.glob("*.md"), *(CODEX_DIR / "agents").glob("*.toml")]
    stale = [
        path
        for path in candidates
        if MARKER in path.read_text(encoding="utf-8")
        and path.relative_to(ROOT).as_posix() not in outputs
    ]
    if CODEX_SKILLS_DIR.is_file():
        raise HarnessError(
            ".agents/skills가 파일입니다(심볼릭 링크가 텍스트로 체크아웃됨). 지우고 render를 다시 돌리세요."
        )
    if CODEX_SKILLS_DIR.is_dir():
        stale.extend(
            path
            for path in sorted(CODEX_SKILLS_DIR.rglob("*"))
            if path.is_file() and path.relative_to(ROOT).as_posix() not in outputs
        )
    return stale


def _remove_empty_dirs(base: Path) -> None:
    if not base.is_dir():
        return
    for path in sorted(base.rglob("*"), key=lambda p: len(p.parts), reverse=True):
        if path.is_dir() and not any(path.iterdir()):
            path.rmdir()


def render(check: bool) -> int:
    outputs = generated()
    drift: list[str] = []
    for rel, text in outputs.items():
        path = ROOT / rel
        if not path.exists():
            drift.append(f"{rel} (없음)")
            continue
        current = path.read_text(encoding="utf-8")
        if _is_marked(rel) and MARKER not in current:
            raise HarnessError(f"생성 대상이 아닌 파일이 자리에 있습니다(마커 없음): {rel}")
        if current != text:
            drift.append(f"{rel} (변경)")
    stale = _stale_files(outputs)
    drift.extend(f"{path.relative_to(ROOT).as_posix()} (원본 없음)" for path in stale)
    if check:
        if drift:
            print("render --check 실패: " + ", ".join(drift))
            return 1
        print(f"render --check OK: {len(outputs)}개 일치")
        return 0
    for rel, text in outputs.items():
        (ROOT / rel).parent.mkdir(parents=True, exist_ok=True)
        (ROOT / rel).write_text(text, encoding="utf-8", newline="\n")
    for path in stale:
        path.unlink()
    _remove_empty_dirs(CODEX_SKILLS_DIR)
    print(f"render 완료: {len(outputs)}개 생성, 변경 {len(drift)}개")
    return 0


def main(argv: list[str] | None = None) -> int:
    for stream in (sys.stdout, sys.stderr):
        if hasattr(stream, "reconfigure"):
            stream.reconfigure(encoding="utf-8", errors="replace")
    parser = argparse.ArgumentParser(description="Claude Code·Codex 역할 파일 생성기")
    subcommands = parser.add_subparsers(dest="command", required=True)
    render_parser = subcommands.add_parser("render", help="역할 파일 생성 또는 drift 검사")
    render_parser.add_argument("--check", action="store_true", help="생성하지 않고 일치만 검사")
    args = parser.parse_args(argv)
    try:
        return render(check=args.check)
    except HarnessError as exc:
        print(f"harness 오류: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main())
